# Lecture 9: Functions #

In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Defining Functions ##  

Example: Create a function that takes a numerical input and triples it: $\textsf{triple}(x)=3\,x$

In [2]:
def triple(x):
    return 3 * x

In [3]:
triple(4)

12

We can also assign a value to a name, and call the function on the name:

In [4]:
num = 4

In [5]:
triple(num)

12

## The Anatomy of a Function ##  
    
```python
def functionname(Arguments_Parameters_Expressions_or_Values):     
      return return_expression
```

## Functions are Type-Agnostic  ## 

In [6]:
triple('ha')

'hahaha'

In [7]:
triple(np.arange(4))

array([0, 3, 6, 9])

### Discussion ###

- What does the following function do?
- What type of input does it take?
- What type of output does it produce?
- What's a good name for the function?

```python
def f(s):     
      return np.round(s / sum(s) * 100, 2)
```

In [8]:
def percent_of_total(s):
    return np.round(s / sum(s) * 100, 2)

In [9]:
first_four=make_array(3,5,6,9)
first_four

array([3, 5, 6, 9])

In [10]:
percent_of_total(first_four)

array([ 13.04,  21.74,  26.09,  39.13])

In [11]:
percent_of_total(make_array(1, 213, 38))

array([  0.4 ,  84.52,  15.08])

### Functions Can Take Multiple Arguments ###

Example: Calculate the Hypotenuse Length of a Right Triangle


Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

In [12]:
def hypotenuse(x, y):
    hypot_squared = (x ** 2 + y ** 2)
    hypot = hypot_squared ** 0.5
    return hypot

In [13]:
hypotenuse(1, 2)

2.23606797749979

In [14]:
hypotenuse(3, 4)

5.0

## Apply ##

In [15]:
ages = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
ages

Person  | Birth Year
Jim     | 1985
Pam     | 1988
Michael | 1967
Creed   | 1904

In [16]:
def name_and_birthyear(name, year):
    out_string= name + " was born in " + str(year) + "."
    return out_string

In [17]:
ages_and_years = ages.apply(name_and_birthyear, 'Person', 'Birth Year')
ages_and_years

array(['Jim was born in 1985.', 'Pam was born in 1988.',
       'Michael was born in 1967.', 'Creed was born in 1904.'],
      dtype='<U25')

In [18]:
ages_and_years[0]

'Jim was born in 1985.'

# Practice

1. Define a function named percent_increase that takes two inputs: small and big. The function returns the the *percent* increase from small to big. For example, if small = 100 and big = 105, then percent_increase(small, big) returns 5.

2. Apply this function to the Gross and Adjusted Gross columns of top_movies.

3. Attach this new column to the table.

In [19]:
top_movies = Table.read_table('top_movies_2017.csv').select("Title", "Gross", "Gross (Adjusted)")
top_movies

Title                            | Gross     | Gross (Adjusted)
Gone with the Wind               | 198676459 | 1796176700
Star Wars                        | 460998007 | 1583483200
The Sound of Music               | 158671368 | 1266072700
E.T.: The Extra-Terrestrial      | 435110554 | 1261085000
Titanic                          | 658672302 | 1204368000
The Ten Commandments             | 65500000  | 1164590000
Jaws                             | 260000000 | 1138620700
Doctor Zhivago                   | 111721910 | 1103564200
The Exorcist                     | 232906145 | 983226600
Snow White and the Seven Dwarves | 184925486 | 969010000
... (190 rows omitted)

In [20]:
def percent_increase(small,big):
    ratio = big/small
    pro_increase= ratio -1 
    percent= pro_increase * 100
    return round(percent,2)

In [23]:
top_movies.apply(percent_increase, 'Gross' , 'Gross (Adjusted)')

array([  8.04070000e+02,   2.43490000e+02,   6.97920000e+02,
         1.89830000e+02,   8.28500000e+01,   1.67800000e+03,
         3.37930000e+02,   8.87780000e+02,   3.22160000e+02,
         4.24000000e+02,   2.61000000e+00,   5.13100000e+02,
         2.00480000e+02,   1.07732000e+03,   1.37500000e+01,
         1.70340000e+02,   1.03050000e+02,   6.91900000e+01,
         8.74500000e+01,   4.08000000e+02,   2.17140000e+02,
         6.24930000e+02,   8.66200000e+02,   7.74000000e+00,
         4.19850000e+02,   1.11620000e+02,   5.79590000e+02,
         2.62510000e+02,   9.64000000e+00,   9.45620000e+02,
         2.37700000e+01,   3.61790000e+02,   1.15211000e+03,
         1.61230000e+02,   4.31600000e+01,   5.13100000e+02,
         4.84870000e+02,   5.30100000e+01,   1.01130000e+02,
         1.10720000e+02,   6.11200000e+02,   9.33720000e+02,
         1.54290000e+02,   1.05387000e+03,   4.84870000e+02,
         4.08000000e+02,   1.51636000e+03,   3.57300000e+01,
         1.26769000e+03,